<?php
 /**
 * NanoRep Widgets Extension
 *
 * @package		NanoRep_Widgets
 * @company		nanoRep. 
 * @website		http://www.nanorep.com
 * @author		Dan Aharon-Shalom
 */	
?>
<!--Order Information-->
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('NanoRep Queries') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
        	<?php if(count($this->getQueries()) > 0): ?>
        		<?php foreach ($this->getQueries() as $query):?>
					<tr><td width="92%"><?php echo $query["query"]?></td><td><?php echo $query["date"]?></td></tr>
				<?php endforeach;?>
			<?php endif;?>
        </table>
    </div>
</div>
