<?php
/**
 * NanoRep Widgets Extension
 *
 * @package		NanoRep_Widgets
 * @company		nanoRep.
 * @website		http://www.nanorep.com
 * @author		Dan Aharon-Shalom
 */
?>
<?php
	if(!is_null($this->getProduct())){
		$_product = $this->getProduct();
	}
	elseif(!is_null(Mage::registry('current_product'))) {
		$_product = Mage::registry('current_product');
	}
	else{
		$_product = null;
	}
?>

<script type='text/javascript'>
	_nRepData["events"] =
	{
		// query: function(query, isAutoQuestion){
// 			
		// }
		
		incomingSearchResults: function(hasResults, isAutoQuestion, query, results){
			
			if(isAutoQuestion == false){
				// if(query == null){
					// query = "Test Question 1";
				// }
				// if(results == null){
					// results = {1: {title: "Title 1", body: "Body 2"}, 2: {title: "Title 2", body: "Body 2"}};
				// }
				// console.log(query);
				// console.log(results);
				new Ajax.Request('<?php echo $this->helper('nanorepwidgets')->getStoreQueryInCookieUrl()?>', {
					method: "post",
					parameters: {
						'query': query,
						'results': JSON.stringify(results),
						'product_id': <?php echo (!is_null($_product)) ? $_product->getId() : 0; ?>
					},
				  	onSuccess: function(response) {
				    	// Handle the response content...
				    	// console.log(response);
					}
				});
			}
		}

	};

</script>
