
<?php
	if(!is_null($this->getProduct())){
		$_product = $this->getProduct();
	}
	elseif(!is_null(Mage::registry('current_product'))) {
		$_product = Mage::registry('current_product');
	}
	else{
		$_product = null;
	}
?>

<?php if($this->helper("nanorepwidgets")->isFloatWidgetActive()): ?>
<div class='nanorep_loadingData' id='nanoRepProxyContainer' style='position:absolute;top:-500px;left:0px;'>
	<span>Loading nanoRep</span>
</div>
<script type='text/javascript'>
	_nRepData['kb'] = '825927';
	_nRepData['float'] = {
		account : '<?php echo $this->helper("nanorepwidgets")->getAccountName();?>',
		cdcVersion : 3,
		cdcFrame : '<?php echo Mage::getBaseUrl(). 'nanorep/index/cdc'; ?>'
	}
	/* API here */;
	(function() {
		var windowLoadFunc = function() {
			var _nRepData = window._nRepData || [];
			_nRepData['windowLoaded'] = true;
			if ( typeof (_nRepData['windowOnload']) === 'function')
				_nRepData['windowOnload']();
		};
		if (window.attachEvent)
			window.attachEvent('onload', windowLoadFunc);
		else if (window.addEventListener)
			window.addEventListener('load', windowLoadFunc, false);
		var sc = document.createElement('script');
		sc.type = 'text/javascript';
		sc.async = true;
		sc.defer = true;
		sc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'my.nanorep.com/widget/scripts/float.js';
		var _head = document.getElementsByTagName('head')[0];
		_head.appendChild(sc);
	})(); 
</script>
<?php endif; ?>