
<?php
	if(!is_null($this->getProduct())){
		$_product = $this->getProduct();
	}
	elseif(!is_null(Mage::registry('current_product'))) {
		$_product = Mage::registry('current_product');
	}
	else{
		$_product = null;
	}
?>

<?php if($this->helper("nanorepwidgets")->isFloatWidgetActive()): ?>
<div class='nanorep_loadingData' id='nanoRepProxyContainer' style='position:absolute;top:-500px;left:0px;'>
</div>
<?php endif; ?>
<script type='text/javascript'>
	<?php 
		if(!is_null($_product)){
			$productID = "";
			$productIdAttribute = Mage::getStoreConfig('nanorepwidgets/account_settings/product_id_attribute');
			if($productIdAttribute == "id"){
				$productID = $_product->getId();
			}
			elseif($productIdAttribute == "sku"){
				$productID = $_product->getsku();
			}
		
			if($productID == ""){
				if($_product->getData($productIdAttribute) != ""){
					$productID = $_product->getData($productIdAttribute);
				}
				else{
					$productID = $_product->getAttributeText($productIdAttribute);
				}
			}
			if($productID == ""){
				$productID = $_product->getId();
			}
		}
	?>
	var _nRepData = _nRepData || [];
	_nRepData["context"] = {
		"Website" : "<?php echo $_SERVER['HTTP_HOST']; ?>"<?php if(!is_null($_product)): ?>,
		"ProductID" : "<?php echo $productID?>"<?php if($_product->getAttributeText('manufacturer') != ""): ?>,
		"Manufacturer" : "<?php echo $_product->getAttributeText('manufacturer'); ?>"<?php endif; ?><?php if(!is_null($_product->getCategory())): ?>,<?php endif; ?>
		<?php endif; ?>
	};
	_nRepData["customParams"] = {
		<?php $this->getCustomerOrdersStatuses(); ?>
	    "userLoggedIn" : "<?php echo $this->isUserLoggedIn(); ?>",
		<?php if(!is_null($_product)): ?>
			"productName": "<?php echo htmlspecialchars($_product->getName()); ?>", 
			<?php $this->getCategory(); ?>
			"ProductID" : "<?php echo $productID?>",
			"Price" : "<?php echo Mage::helper('core')->currency($_product->getFinalPrice(), true, false); ?>",
			<?php $this->getProductRelatedProducts($_product); ?>
			<?php $this->getProductUpSellsProducts($_product); ?>
			<?php $this->getProductCrossSellProducts($_product); ?>
			<?php $this->getProductAttributes($_product); ?>
		<?php endif; ?>
	};
	
	function parseOrdersNrepData(dataName, title)
    {
        var s = [];
        var d = _nRepData["customParams"][dataName];
        var col = 3;
        var count = 0;
        s.push("<table class='orderNRD' width='100%'><tr><td colspan='" + col + "' class='title'><b>" + title + "</b></td></tr><tr>");
        for (var i in d)
        {
            var product = d[i];
            if (typeof (product) != "object") continue;
            if (count == col)
            {
                s.push("</tr><tr>");
                count = 0;
            }
            s.push("<td class='product'>");
            s.push("<div class='img'><img src='");
            s.push(product.image_url);
            s.push("' width='125' height='125'/></div><div class='link'><a href='");
            s.push(product.url);
            s.push("'>");
            s.push(product.name);
            s.push("</a></div></td>");
            ++count;
        }
        s.push("</tr></table>");
        _nRepData["customParams"][dataName + '_string'] = s.join('');
    }
    (function (){
        if (_nRepData["customParams"])
        {
            if (_nRepData["customParams"]['orders'])
            {
                var s = [];
                var d = _nRepData["customParams"]['orders'];
                s.push("<table class='orderNRD' width='100%'><tr class='orders'><th>Order #</th><th>Status</th><th>Details</th></tr>");
                for (var i in d)
                {
                    for (var j in d[i])
                    {
                        if (isNaN(j)) continue;
                        var order = d[i][j];
                        if (typeof (order) != "object") continue;
                        s.push("<tr><td><b>");
                        s.push(j);
                        s.push("</b></td><td>");
                        s.push(order.status);
                        s.push("</td><td><a href='");
                        s.push(order.link);
                        s.push("'>Click for details</a></td></tr>");
                    }
                }
                s.push("</table>");
                _nRepData["customParams"]['orders_string'] = s.join('');
            }
            if (_nRepData["customParams"]['relatedProducts'])
            {
                parseOrdersNrepData('relatedProducts', "You may also be interested in the following product(s):");
            }
            if (_nRepData["customParams"]['upSellsProducts'])
            {
                parseOrdersNrepData('upSellsProducts', "You may also be interested in the following product(s):");
            }
            if (_nRepData["customParams"]['crossSellsProducts'])
            {
                parseOrdersNrepData('crossSellsProducts', "You may also be interested in the following product(s):");
            }
        }
    })();
</script>
