<?php
/**
 * NanoRep Widgets Extension
 *
 * @package		NanoRep_Widgets
 * @company		nanoRep.
 * @website		http://www.nanorep.com
 * @author		Dan Aharon-Shalom
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-Equiv="Cache-Control" Content="no-cache, no-store, must-revalidate">
		<meta http-Equiv="Pragma" Content="no-cache">
		<meta http-Equiv="Expires" Content="0">
	
		<title>nanoRep CDC Relay v3</title>
		<script type="text/javascript">
		    window.scriptLoaded = false;
		    window.pageLoaded = false;
		    window.fileVersion = 3;

		    //////////////////////////////////////////////////////////////////////////
            // handlers
		    window.onload = function ()
		    {
		        window.pageLoaded = true;
		        if (window.scriptLoaded) nanoRep.CDC.Relay.start();
		    }
            var scriptLoaded_handler = function()
            {
                window.scriptLoaded = true;
                if (window.pageLoaded) nanoRep.CDC.Relay.start();
            }

            //////////////////////////////////////////////////////////////////////////
            // Loading cdc relay script
            var s = document.createElement("script");
            s.type = 'text/javascript';
            s.async = true;
            s.defer = true;

            // non-ie browsers
            if (navigator.appVersion.indexOf("MSIE") === -1)
            {
                s.onload = scriptLoaded_handler;
            }
            // ie browsers
            else
            {
                s.onreadystatechange = function ()
                {
                    if (this.readyState !== 'complete' && this.readyState !== 'loaded') return;
                    scriptLoaded_handler();
                }
            }
            var args = window.location.search;
            if (args)
            {
                args = args.substring(1);
                var ndx = args.indexOf("srv=");
                if (ndx !== -1)
                {
                    args = args.substring(ndx+4);
                    var src, tag;
                    ndx = args.indexOf("&");
                    if (ndx === -1)
                    {
                        src = args + "/common/cdc/cdcRelay.js";
                    }
                    else
                    {
                        tag = args.substring(ndx + 1);
                        src = args.substring(0, ndx) + "/common/cdc/cdcRelay.js?" + tag;
                    }
                    s.src = src;
                    document.getElementsByTagName("head")[0].appendChild(s);
                }
            }
        </script>
	</head>
	<body style='margin:0;padding:0'>
		<div id='log' style='height:1050px'></div>
	</body>
</html>